#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~ ~/development -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    # if in tmux switch upon creation
    # if not in tmux attach upon creation

    if [[ -z $TMUX ]]; then
        tmux new-session -s $selected_name -c $selected
    else
        tmux new-session -ds $selected_name -c $selected
        tmux switch-client -t $selected_name
    fi

else 

    if [[ -z $TMUX ]]; then
        tmux attach-session -t $selected_name
    else
        tmux switch-client -t $selected_name
    fi

fi


